[build-system]
requires = [
  "setuptools",
  "setuptools-scm>=8",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-r a"

[tool.ruff]
line-length = 120